/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unpa.winforms.ferreteria;

import unpa.winforms.ferreteria.el.Alumno;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chee <chee_unp@edu.mx>
 */
public class FrmAlumno extends javax.swing.JFrame {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        checBoxActivo = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("java.aplication");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(102, 102, 102));
        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Alumno:"));
        Panel.setForeground(new java.awt.Color(102, 102, 102));
        Panel.setToolTipText("Alumno");
        Panel.setAutoscrolls(true);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, 30));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        Panel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, 40));

        jLabel2.setText("Apellido Paterno:");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setText("Apellido Materno:");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setText("Direccion:");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel5.setText("Telefono:");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        Panel.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, 40));
        Panel.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 169, 250, 40));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        Panel.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 250, 40));
        Panel.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 250, 40));

        btnInsertar.setText("Insertar");
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });
        Panel.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 80, 30));

        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 80, 40));

        jLabel7.setText("Matricula:");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 20));
        Panel.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 250, 40));

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        Panel.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, 30));

        checBoxActivo.setText("Activo");
        checBoxActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checBoxActivoActionPerformed(evt);
            }
        });
        Panel.add(checBoxActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 80, 40));

        jButton2.setText("Eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 80, 30));

        btnConsultar.setText("Consultar");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        Panel.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 100, 30));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        try {
            // this.registrar();
        } catch (Exception ex) {
            Logger.getLogger(FrmAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        try {
            //this.actualizar();
        } catch (Exception ex) {
            Logger.getLogger(FrmAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            //this.eliminarLogicamente();
        } catch (Exception ex) {
            Logger.getLogger(FrmAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void checBoxActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checBoxActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checBoxActivoActionPerformed

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked

//   System.out.println("probando la consulta");
        try {
            //   this.consultar();
            //     System.out.println(testuniversity.AlumnoQry(this.alumno).getNombre());
        } catch (Exception ex) {
            Logger.getLogger(FrmAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JCheckBox checBoxActivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form FrmAlumno
     */
    testUniversity testuniversity = null;
    Alumno alumno = null;
    private String matriculaAux;

    public FrmAlumno() {
        this.initComponents();
        this.Inicializar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlumno().setVisible(true);
            }
        });
    }

    private void Inicializar() {
        testuniversity = new testUniversity();
        alumno = new Alumno();
        this.LimpiarCampos();
    }

    private void LimpiarCampos() {
        if (alumno != null) {
            alumno = new Alumno();
        }
        this.txtMatricula.setText("");
        this.txtNombre.setText("");
        this.txtApPaterno.setText("");
        this.txtApMaterno.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
        this.alumno.setActivo(0);
        //this.txtActivo.setText("");
    }

    private boolean ValidarCampos() {
        boolean validar = false;

        if (!this.txtNombre.getText().isEmpty()
                && !this.txtApPaterno.getText().isEmpty() && !this.txtApMaterno.getText().isEmpty()
                && !this.txtDireccion.getText().isEmpty() && !this.txtTelefono.getText().isEmpty()) {

            /* if(this.txtMatricula.getText() != "" || this.txtNombre.getText() != "" || 
           this.txtApPaterno.getText() != "" || this.txtApMaterno.getText() != "" || 
           this.txtDireccion.getText() != "" || this.txtTelefono.getText() != "" || this.txtActivo.getText() != ""){*/
            validar = true;

        } else {
            validar = false;
        }

        return validar;
    }

    private boolean LlenarAtributos() {
        boolean verificador = false;

        if (this.ValidarCampos()) {
            alumno.setNombre(this.txtNombre.getText());
            alumno.setAp_Paterno(this.txtApPaterno.getText());
            alumno.setAp_Materno(this.txtApMaterno.getText());
            alumno.setDireccion(this.txtDireccion.getText());
            alumno.setTelefono(this.txtTelefono.getText());
            //  a.setActivo(Integer.parseInt(this.txtActivo.getText()));
            alumno.setActivo(1);

            verificador = true;
        } else {
            JOptionPane.showMessageDialog(this, "Completar campos vacios");
            verificador = false;
        }

        return verificador;
    }

    private void registrar() throws Exception {
        int verificador = 0;

        if (this.LlenarAtributos()) {

            this.matriculaAux = testuniversity.AlumnoAdd(alumno);//aqui recupero mi matricula del procedimiento
            //   System.out.println("probabdo = " + verificador);
            System.out.println("recuperado = " + this.matriculaAux);

            if (matriculaAux != null) {
                JOptionPane.showMessageDialog(this, "Datos registradados");
                this.LimpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar");
            }
        }// else {
        // JOptionPane.showMessageDialog(this, "Verifica tus datos");
        //}

    }

    private void consultar() throws Exception {
        this.LimpiarCampos();
        this.alumno.setMatricula(matriculaAux);
        this.alumno = testuniversity.AlumnoQry(this.alumno);
        System.out.println("probando en el metodo consultar" + alumno.getNombre());
        this.txtNombre.setText(alumno.getNombre());
        this.txtApPaterno.setText(alumno.getAp_Paterno());
        this.txtApMaterno.setText(alumno.getAp_Materno());
        this.txtDireccion.setText(alumno.getDireccion());
        this.txtTelefono.setText(alumno.getTelefono());
        System.out.println(alumno.getMatricula());
    }

    private void actualizar() throws Exception {
        int verificador = 0;
        //this.matriculaAux=this.txtMatricula.getText();
        alumno.setMatricula(this.matriculaAux);
        if (this.LlenarAtributos()) {
            verificador = testuniversity.AlumnoUpd(alumno);

            System.out.println("probabdo = " + verificador);

            if (verificador == 1) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo Actualizar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifica tus datos");
        }
    }

    private void eliminarLogicamente() throws Exception {
        int verificador;
        // alumno.setMatricula(this.txtMatricula.getText());
        alumno.setMatricula(this.matriculaAux);
        if (this.checBoxActivo.isSelected() == true) {
            alumno.setActivo(1);
        } else {
            alumno.setActivo(0);
        }
        verificador = testuniversity.AlumnoELogic(alumno);
        if (verificador == 1) {
            JOptionPane.showMessageDialog(this, "Eliminacion Exitosa");
        } else {
            JOptionPane.showMessageDialog(this, "Eliminacion Fallida");
        }
    }
}
