/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unpa.winforms.ferreteria;

import java.awt.Color;
import java.sql.Connection;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import unpa.winforms.ferreteria.bll.BLL_Empleado;
import unpa.winforms.ferreteria.bll.BLL_EmpleadoTelefono;
import unpa.winforms.ferreteria.bll.BLL_Proveedor;
import unpa.winforms.ferreteria.bll.BLL_ProveedorTelefono;
import unpa.winforms.ferreteria.bll.BLL_Usuario;
import unpa.winforms.ferreteria.el.Empleado;
import unpa.winforms.ferreteria.el.EmpleadoTelefono;
import unpa.winforms.ferreteria.el.Proveedor;
import unpa.winforms.ferreteria.el.ProveedorTelefono;
import unpa.winforms.ferreteria.el.Usuario;
import unpa.winforms.ferreteria.util.DbUtil;

/**
 *
 * @author chee <chee_unp@edu.mx>
 */
public class FrmEmpleado extends javax.swing.JFrame {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        comboxEmpleado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcomboxTelefono = new javax.swing.JComboBox<>();
        txtLada = new javax.swing.JTextField();
        txtExtension = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnActualizarTelefono = new javax.swing.JButton();
        btnEliminarTelefono = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jComboDia = new javax.swing.JComboBox<>();
        jComboMes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Datos_Empleado:"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo Empleado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabel3.setText("ID_Empleado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 260, 30));

        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 270, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Dirreccion:"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo Postal:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));

        jLabel5.setText("Calle:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 20));

        jLabel6.setText("Ciudad:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 50, 20));

        jLabel11.setText("Colonia:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 20));
        jPanel2.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 270, 30));
        jPanel2.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 30));
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 30));

        txtCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPostalActionPerformed(evt);
            }
        });
        txtCodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPostalKeyReleased(evt);
            }
        });
        jPanel2.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 480, 210));

        comboxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Cajero", "Mostrador", "Limpieza", "Contador", "Bodeguero", "Repartidor" }));
        jPanel1.add(comboxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel7.setText("Apellido Paterno:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setText("Nombre Empleado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 270, 30));

        jLabel9.setText("Apellido Materno:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));
        jPanel1.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 270, 30));

        jLabel10.setText("Fecha Nacimiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Telefonos:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Numero");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel12.setText("Extension");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel13.setText("Lada");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel14.setText("Tipo Telefono:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jcomboxTelefono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Casa", "Oficina" }));
        jPanel3.add(jcomboxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtLada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadaActionPerformed(evt);
            }
        });
        jPanel3.add(txtLada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 80, 30));
        jPanel3.add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 70, 30));

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        jPanel3.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 140, 30));

        jButton1.setText("Agregar Telefono");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btnActualizarTelefono.setText("Actualizar Telefono");
        btnActualizarTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarTelefonoMouseClicked(evt);
            }
        });
        jPanel3.add(btnActualizarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        btnEliminarTelefono.setText("Eliminar Telefono");
        jPanel3.add(btnEliminarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 480, 140));

        btnConsultar.setText("Consultar");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 100, 40));

        btnInsertar.setText("Insertar");
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 90, 40));

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 90, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Datos De Acceso:"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 88, -1, -1));

        jLabel15.setText("Contraseña:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel16.setText("Usuario:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyReleased(evt);
            }
        });
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 210, 30));

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 210, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 390, 140));

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 100, 40));

        jComboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 50, 30));

        jComboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(jComboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, 30));

        jLabel17.setText("Dia");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 30, -1));

        jLabel18.setText("Mes");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 20));

        jLabel19.setText("Año");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAñoKeyReleased(evt);
            }
        });
        jPanel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 910, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void txtLadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadaActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    //comprobar que si sean los dijitos entre 7- 10 de numero telefonico y que sean letras
    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        Pattern pat = Pattern.compile("[0-9\\s]{7,10}");
        Matcher mat = pat.matcher(this.txtNumero.getText().trim());
        if (mat.matches()) {
            this.txtNumero.setBackground(null);
            this.areaNumero = true;
        } else {
            this.txtNumero.setBackground(Color.RED);
            this.areaNumero = false;
        }
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        try {
            // this.registrar();
        } catch (Exception ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        Pattern pat = Pattern.compile("[a-zA-Z0-9\\s]{5,10}");
        Matcher mat = pat.matcher(this.txtUsuario.getText().trim());
        if (mat.matches()) {
            this.txtUsuario.setBackground(null);
            this.areaCuentaUsuario = true;
        } else {
            this.txtUsuario.setBackground(Color.RED);
            this.areaCuentaUsuario = false;
        }
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void txtContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyReleased
        Pattern pat = Pattern.compile("[a-zA-Z0-9\\s]{5,10}");
        Matcher mat = pat.matcher(this.txtContraseña.getText().trim());
        if (mat.matches()) {
            this.txtContraseña.setBackground(null);
            this.areaContraseña = true;
        } else {
            this.txtContraseña.setBackground(Color.RED);
            this.areaContraseña = false;
        }
    }//GEN-LAST:event_txtContraseñaKeyReleased

    private void txtCodigoPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPostalKeyReleased
        Pattern pat = Pattern.compile("[0-9\\s]{5}");
        Matcher mat = pat.matcher(this.txtCodigoPostal.getText().trim());
        if (mat.matches()) {
            this.txtCodigoPostal.setBackground(null);
            this.areaCodigoPostal = true;
        } else {
            this.txtCodigoPostal.setBackground(Color.RED);
            this.areaCodigoPostal = false;
        }
    }//GEN-LAST:event_txtCodigoPostalKeyReleased

    private void txtAñoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyReleased
        Pattern pat = Pattern.compile("[0-9\\s]{4}");
        Matcher mat = pat.matcher(this.txtAño.getText().trim());
        if (mat.matches()) {
            this.txtAño.setBackground(null);
            this.areaAño = true;
        } else {
            this.txtAño.setBackground(Color.RED);
            this.areaAño = false;
        }
    }//GEN-LAST:event_txtAñoKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            //  this.registrarTelefono();
        } catch (Exception ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        try {
            //  this.consultar();
            this.txtExtension.setText("");
        } catch (Exception ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnActualizarTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTelefonoMouseClicked
        try {
            //   this.actalizarTelefono();
            this.txtExtension.setText("");
        } catch (Exception ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarTelefonoMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        try {
            // this.actualizar();
            this.txtExtension.setText("");
        } catch (Exception ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            //  this.eliminar();
        } catch (Exception ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void txtCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarTelefono;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTelefono;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboxEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboDia;
    private javax.swing.JComboBox<String> jComboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> jcomboxTelefono;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtLada;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    testUniversity testuniversity = null;
    Empleado empleado = null;

    Usuario usuario = null;
    BLL_Empleado bbl_Empleado = null;
    BLL_EmpleadoTelefono bbl_EmpleadoTelefono = new BLL_EmpleadoTelefono();
    BLL_Usuario bbl_usuario = null;
    EmpleadoTelefono empleadoTelefono = null;
    private Connection dbCon;

    testUniversity u = new testUniversity();
    LinkedList listaTelefonoEmpleado = new LinkedList();
    private String idEmpleadoTelefono;
    private String idUsuarioAux;
    private String idEmpleadoAux;
    ///variables para comprobar las cajas de texto

    private boolean areaNumero;
    private boolean areaCuentaUsuario;
    private boolean areaContraseña;
    private boolean areaNombre;
    private boolean areaCodigoPostal;
    private boolean areaAño;

    public FrmEmpleado() {
        initComponents();
        this.Init();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    public void Init() {
        try {
            empleado = new Empleado();
            usuario = new Usuario();
            dbCon = DbUtil.getInstance().getConnection();

        } catch (Exception e) {
        }
    }

    private void LimpiarCampos() {
        if (empleado != null) {
            empleado = new Empleado();
        }
        this.txtNombreEmpleado.setText("");
        this.txtApellidoPaterno.setText("");
        this.txtApellidoMaterno.setText("");
        this.txtAño.setText("");
        this.txtUsuario.setText("");
        this.txtContraseña.setText("");
        this.txtUsuario.setText("");
        this.txtCalle.setText("");
        this.txtCiudad.setText("");
        this.txtCodigoPostal.setText("");
        this.txtLada.setText("");
        this.txtExtension.setText("");
        this.txtLada.setText("");
    }

    private boolean ValidarCampos() {
        boolean validar = false;
        if (!this.txtNombreEmpleado.getText().isEmpty()
                && !this.txtApellidoPaterno.getText().isEmpty()
                && !this.txtApellidoMaterno.getText().isEmpty()
                && !this.txtAño.getText().isEmpty()
                && !this.txtUsuario.getText().isEmpty()
                && !this.txtContraseña.getText().isEmpty()
                && !this.txtCalle.getText().isEmpty()
                && !this.txtColonia.getText().isEmpty()
                && !this.txtCiudad.getText().isEmpty()
                && !this.txtCodigoPostal.getText().isEmpty()
                && !this.txtLada.getText().isEmpty()
                && !this.txtNumero.getText().isEmpty()) {
            validar = true;
        } else {
            validar = false;
        }
        return validar;
    }

    private boolean LlenarAtributos() {
        boolean verificador = false;
        String mesSeleccionado = String.valueOf(this.jComboMes.getSelectedIndex() + 1);
        String diaSeleccionado = String.valueOf(this.jComboDia.getSelectedIndex() + 1);
        String fechaNacimiento = diaSeleccionado + "/" + mesSeleccionado + "/" + this.txtAño.getText();
        System.out.println("diaSeleccionado " + diaSeleccionado);
        System.out.println("mesSeleccionado" + mesSeleccionado);
        System.out.println("fechaNacimiento" + fechaNacimiento);

        int indiceComboxTipoEmplead = this.comboxEmpleado.getSelectedIndex();
        empleado = new Empleado();
        this.usuario = new Usuario();
        if (this.ValidarCampos()) {
            System.out.println(this.txtNombreEmpleado.getText());
            empleado.setId_TipoEmpleado(indiceComboxTipoEmplead + 1);
            empleado.setNombre(this.txtNombreEmpleado.getText());
            empleado.setApPaterno(this.txtApellidoPaterno.getText());
            empleado.setApMaterno(this.txtApellidoMaterno.getText());
            empleado.setFechaNacimiento(fechaNacimiento);
            empleado.setCalle(this.txtCalle.getText());
            empleado.setColonia(this.txtColonia.getText());
            empleado.setCiudad(this.txtCiudad.getText());
            empleado.setCodigoPostal(Integer.parseInt(this.txtCodigoPostal.getText()));
            usuario.setCuentaUsuario(this.txtUsuario.getText());
            usuario.setContraseña(this.txtContraseña.getText());
            verificador = true;
        } else {
            JOptionPane.showMessageDialog(this, "Completar campos vacios");
            verificador = false;
        }
        return verificador;
    }

    private boolean LlenarAtributosTelefono() {
        boolean verificador = false;
        //empleadoTelefono = new EmpleadoTelefono();
        int indiceCombox = this.jcomboxTelefono.getSelectedIndex();
        empleadoTelefono = new EmpleadoTelefono();
        if (this.ValidarCampos()) {
            System.out.println(this.txtNumero.getText());
            this.empleadoTelefono.setIdEmpleado(this.idEmpleadoAux);// se inserta el idProveedor reuperado en el Telefono
            this.empleadoTelefono.setLada(this.txtLada.getText());
            this.empleadoTelefono.setNumero(this.txtNumero.getText());
            this.empleadoTelefono.setTipoTelefono(indiceCombox + 1);//aqui se le agrega el tipo de telefono sleccionado
            if (this.txtExtension.getText().isEmpty() == true) {
                this.empleadoTelefono.setExtension(0);
            } else {
                this.empleadoTelefono.setExtension(Integer.parseInt(this.txtExtension.getText()));
            }
            verificador = true;
        } else {
            JOptionPane.showMessageDialog(this, "Completar campos vacios");
            verificador = false;
        }
        return verificador;
    }

    private void registrar() throws Exception {
        bbl_Empleado = new BLL_Empleado();
        bbl_EmpleadoTelefono = new BLL_EmpleadoTelefono();
        bbl_usuario = new BLL_Usuario();
        int verificador = 0;
        if (this.LlenarAtributos()) {
            this.idUsuarioAux = bbl_usuario.AddToDataBaseUsuario(dbCon, this.usuario);//aqui recupero mi matricula del procedimiento
            System.out.println("id recuperado = " + this.idUsuarioAux);
            this.empleado.setId_Usuario(idUsuarioAux);

            this.idEmpleadoAux = bbl_Empleado.AddToDataBaseEmpleado(dbCon, empleado);
            System.out.println(idEmpleadoAux);

            if (this.LlenarAtributosTelefono()) {
                verificador = bbl_EmpleadoTelefono.AddToDataBaseEmpleadoTelefono(dbCon, this.empleadoTelefono);
                System.out.println("verificador=" + verificador);
            }
            if (idUsuarioAux != null && idEmpleadoAux != null && verificador != 0) {
                JOptionPane.showMessageDialog(this, "Datos registradados");
                // this.LimpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar");
            }
        }
    }

    private void registrarTelefono() throws Exception {
        int indiceCombox = this.jcomboxTelefono.getSelectedIndex();
        int verificador = 0;
        if (indiceCombox + 1 == 1) {
            JOptionPane.showMessageDialog(this, "El telefono ya existe");
        } else {
            if (this.LlenarAtributosTelefono()) {
                verificador = bbl_EmpleadoTelefono.AddToDataBaseEmpleadoTelefono(dbCon, empleadoTelefono);
                if (verificador != 0) {
                    JOptionPane.showMessageDialog(this, "Telefono registradado");
                    //this.LimpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el telefono");
                }
            }
        }
        this.txtExtension.setText("");//limpiar en la caja de Extension para que no guarde

    }

    private void consultar() throws Exception {
        this.LimpiarCampos();
        empleado = new Empleado();
        usuario = new Usuario();
        bbl_EmpleadoTelefono = new BLL_EmpleadoTelefono();
        bbl_Empleado = new BLL_Empleado();
        bbl_usuario = new BLL_Usuario();
        String idUsuarioAux;
        int tipoEmpleado;

        System.out.println(this.txtIdEmpleado.getText());
        empleado = bbl_Empleado.QueryDataBase(dbCon, this.txtIdEmpleado.getText());
        tipoEmpleado = empleado.getId_TipoEmpleado();
        this.txtNombreEmpleado.setText(empleado.getNombre());
        this.txtApellidoPaterno.setText(empleado.getApPaterno());
        this.txtApellidoMaterno.setText(empleado.getApMaterno());
        this.txtCalle.setText(empleado.getCalle());
        this.txtColonia.setText(empleado.getColonia());
        this.txtCiudad.setText(empleado.getCiudad());
        this.txtCodigoPostal.setText(String.valueOf(empleado.getCodigoPostal()));

        String fNacimiento[] = empleado.getFechaNacimiento().split("/");
        this.jComboDia.setSelectedIndex(Integer.parseInt(fNacimiento[0]) - 1);
        this.jComboMes.setSelectedIndex(Integer.parseInt(fNacimiento[1]) - 1);
        this.comboxEmpleado.setSelectedIndex(tipoEmpleado - 1);
        this.txtAño.setText(fNacimiento[2]);

        idUsuarioAux = empleado.getId_Usuario();
        this.idEmpleadoAux = empleado.getId_Empleado(); //obtiene el id del proveedor

        usuario = bbl_usuario.QueryUsuarioDataBase(dbCon, idUsuarioAux);
        this.txtUsuario.setText(usuario.getCuentaUsuario());
        this.txtContraseña.setText(usuario.getContraseña());
        this.idUsuarioAux = usuario.getIdUsuario();
        this.empleadoTelefono = new EmpleadoTelefono();
        this.obtenerTodosLosTelefonosEmpleado();

        if (this.listaTelefonoEmpleado.size() > 0) {
            empleadoTelefono = (EmpleadoTelefono) listaTelefonoEmpleado.get(this.jcomboxTelefono.getSelectedIndex());
            this.txtLada.setText(empleadoTelefono.getLada());
            if (empleadoTelefono.getExtension() == 0) {
                this.txtExtension.setText(" ");
            } else {
                this.txtExtension.setText(String.valueOf(empleadoTelefono.getExtension()));
            }
            this.txtNumero.setText(empleadoTelefono.getNumero());
        } else {
            JOptionPane.showMessageDialog(this, "No existen Telefonos");
        }
    }

    public void actalizarTelefono() throws Exception {
        int areaTelefono = 0;
        int indiceCombox = this.jcomboxTelefono.getSelectedIndex();

        bbl_EmpleadoTelefono = new BLL_EmpleadoTelefono();
        empleadoTelefono = new EmpleadoTelefono();
        this.empleadoTelefono = (EmpleadoTelefono) (this.listaTelefonoEmpleado.get(indiceCombox));
        empleadoTelefono.setIdEmpleado(empleado.getId_Empleado());
        if (this.LlenarAtributosTelefono()) {
            areaTelefono = bbl_EmpleadoTelefono.updateEmpleadoTelefonoDatabase(dbCon, empleadoTelefono);
            System.out.println("verificador: " + areaTelefono);
            if (areaTelefono == 1) {
                JOptionPane.showMessageDialog(this, "Telefono Actualizado Exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Actualizacion Fallido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifica tus Datos");
        }
    }

    public void actualizar() throws Exception {
        int areaEmpleado = 0;
        int areaUsuario = 0;
        bbl_Empleado = new BLL_Empleado();
        bbl_usuario = new BLL_Usuario();
        empleado.setId_Empleado(this.idEmpleadoAux);

        if (this.LlenarAtributos()) {
            areaEmpleado = bbl_Empleado.updateEmpleadoDataBase(dbCon, empleado);
            areaUsuario = bbl_usuario.updateEmpleadoDataBase(dbCon, usuario);
            System.out.println("areaEmpleado = " + areaEmpleado);
            System.out.println("areaUsuario = " + areaUsuario);
            if (areaEmpleado == 1 && areaUsuario == 1) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo Actualizar");
            }
            this.actalizarTelefono();
        } else {
            JOptionPane.showMessageDialog(this, "Verifica tus datos");
        }
        this.txtExtension.setText("");
    }

    private void eliminar() throws Exception {
        bbl_Empleado = new BLL_Empleado();
        bbl_EmpleadoTelefono = new BLL_EmpleadoTelefono();
        bbl_usuario = new BLL_Usuario();
        int verificadorProveedor, verificadorTelefono, verificadorUsuario;
        empleado.setId_Empleado(this.idEmpleadoAux);
        usuario.setIdUsuario(idUsuarioAux);
        verificadorTelefono = bbl_EmpleadoTelefono.deleteEmpleadoTelefonoDatabase(dbCon, empleado);
        verificadorProveedor = bbl_Empleado.deleteEmpleadoDatabase(dbCon, empleado);
        verificadorUsuario = bbl_usuario.deleteUsuarioDatabase(dbCon, usuario);
        if (verificadorTelefono == 1 && verificadorProveedor == 1) {
            JOptionPane.showMessageDialog(this, "Proveedor Eliminado");
        } else {
            JOptionPane.showMessageDialog(this, "Eliminacion Fallida, Proveedor no Eliminado");
        }
    }

    private void obtenerTodosLosTelefonosEmpleado() {
        try {
            BLL_ProveedorTelefono bbl_ProveedorTelefono = new BLL_ProveedorTelefono();
            this.listaTelefonoEmpleado.addAll(bbl_EmpleadoTelefono.QueryEmpleadoTelefonosDataBase(dbCon, idEmpleadoAux));
        } catch (Exception e) {
            System.out.println("Problemas al obtener todosd los Telefonos proveedores ");
        }
    }

}
