/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unpa.winforms.ferreteria;

import unpa.winforms.ferreteria.el.ModeloTablaProveedor;
import unpa.winforms.ferreteria.el.Proveedor;
import unpa.winforms.ferreteria.el.ProveedorTelefono;
import java.sql.Connection;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import unpa.winforms.ferreteria.bll.BLL_Proveedor;
import unpa.winforms.ferreteria.bll.BLL_ProveedorTelefono;
import unpa.winforms.ferreteria.dal.DAL_Proveedor;
import unpa.winforms.ferreteria.util.DbUtil;

/**
 *
 * @author chee <chee_unp@edu.mx>
 */
public class FrmProveedor extends javax.swing.JFrame {

    /**
     * Creates new form FrmProveedor
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        jComboxTelefono = new javax.swing.JComboBox<>();
        txtLada = new javax.swing.JTextField();
        txtExtension = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnRegistrarTelefono = new javax.swing.JButton();
        btnActualizarTelefono = new javax.swing.JButton();
        btnEliminarTelefono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos Proveedor:");
        setName("Proveedor"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Proveedor:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Direccion:"));
        jPanel2.setToolTipText("Direccion:");
        jPanel2.setName("Drireccion:"); // NOI18N

        jLabel3.setText("Colonia:");

        jLabel4.setText("Ciudad:");

        jLabel2.setText("Calle:");

        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });

        jLabel5.setText("Código Postal:");

        txtCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPostalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtColonia)
                            .addComponent(txtCalle)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 450, 250));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, -1, -1));

        jLabel6.setText("ID Proveedor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));
        jPanel1.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 290, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefono:"));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProveedor.setBorder(new javax.swing.border.MatteBorder(null));
        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo_Telefono", "Lada", "Extension", "Numero"
            }
        ));
        jScrollPane2.setViewportView(tablaProveedor);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 510, 20));

        jComboxTelefono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Casa", "Oficina" }));
        jPanel3.add(jComboxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));
        jPanel3.add(txtLada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, 30));
        jPanel3.add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, 30));
        jPanel3.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 150, 30));

        btnRegistrarTelefono.setText("Agregar Telefono");
        btnRegistrarTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarTelefonoMouseClicked(evt);
            }
        });
        jPanel3.add(btnRegistrarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 120, 130, -1));

        btnActualizarTelefono.setText("ActualizarTelefono");
        btnActualizarTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarTelefonoMouseClicked(evt);
            }
        });
        btnActualizarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTelefonoActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        btnEliminarTelefono.setText("Eliminar Telefono");
        btnEliminarTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarTelefonoMouseClicked(evt);
            }
        });
        jPanel3.add(btnEliminarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 540, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 570, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        try {
            this.consultar();
            // this.obtenerTodosLosProveedor("311c89e9-70c7-11e8-9efa-28d244202eee");
         //   this.txtExtension.setText("");
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        try {
            this.registrar();
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();

    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        try {
            this.actualizar();
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            this.eliminar();
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnActualizarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTelefonoActionPerformed

    private void btnActualizarTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTelefonoMouseClicked
        try {
            this.actalizarTelefono();
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error en boton Actualizar telefono");
        }
    }//GEN-LAST:event_btnActualizarTelefonoMouseClicked

    private void btnRegistrarTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTelefonoMouseClicked
        try {
            this.registrarTelefono();
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarTelefonoMouseClicked

    private void btnEliminarTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTelefonoMouseClicked
        try {
            this.eliminarTelefono();
        } catch (Exception ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarTelefonoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarTelefono;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTelefono;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarTelefono;
    private javax.swing.JComboBox<String> jComboxTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProveedor;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtLada;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
  
    private ModeloTablaProveedor modelo = null;
    private FrmProveedor padre;
    testUniversity testuniversity = null;
    Proveedor proveedor = null;
    private String idProveedorAux;
    BLL_Proveedor bbl_Proveedor = null;
    BLL_ProveedorTelefono bbl_ProveedorTelefono = new BLL_ProveedorTelefono();
    ProveedorTelefono proveedorTelefono = null;
    private Connection dbCon;
    
    testUniversity u = new testUniversity();
    LinkedList listaTelefonoProveedor = new LinkedList();
    private String idProveedorTelefono;
    
    
    
    public FrmProveedor() {
        initComponents();
        this.Init();
        this.crearComboBoxdProveedorTelefono();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProveedor().setVisible(true);

            }

        }
        );

    }

    public void Init() {
        try {
            proveedor = new Proveedor();
            dbCon = DbUtil.getInstance().getConnection();
            this.crearComboBoxdProveedorTelefono();
        } catch (Exception e) {

        }
    }

    public void obtenerTodosLosProveedor(String idProveedor) {
        try {
            modelo = new ModeloTablaProveedor(dbCon, idProveedor);
            tablaProveedor.setModel(modelo);
        } catch (Exception e) {

        }
    }

    private void LimpiarCampos() {
        if (proveedor != null) {
            proveedor = new Proveedor();
        }
        this.txtNombre.setText("");
        this.txtCalle.setText("");
        this.txtColonia.setText("");
        this.txtCiudad.setText("");
        this.txtCodigoPostal.setText("");
    }

    private boolean ValidarCampos() {
        boolean validar = false;

        if (!this.txtNombre.getText().isEmpty()
                && !this.txtCalle.getText().isEmpty()
                && !this.txtColonia.getText().isEmpty()
                && !this.txtCiudad.getText().isEmpty()
                && !this.txtCodigoPostal.getText().isEmpty()) {

            validar = true;

        } else {
            validar = false;
        }
        return validar;
    }

    private boolean ValidarCamposTelefono() {
        boolean validar = false;

        if (!this.txtLada.getText().isEmpty() && !this.txtNumero.getText().isEmpty()) {
            validar = true;
        } else {
            validar = false;
        }
        return validar;
    }

    private boolean LlenarAtributos() {
        boolean verificador = false;

        if (this.ValidarCampos()) {
            System.out.println(this.txtNombre.getText());

            proveedor.setNombre(this.txtNombre.getText());
            proveedor.setCalle(this.txtCalle.getText());
            proveedor.setColonia(this.txtColonia.getText());
            proveedor.setCiudad(this.txtCiudad.getText());
            proveedor.setCodigoPostal(Integer.parseInt(this.txtCodigoPostal.getText()));
            //  a.setActivo(Integer.parseInt(this.txtActivo.getText()));

            verificador = true;
        } else {
            JOptionPane.showMessageDialog(this, "Completar campos vacios");
            verificador = false;
        }
        return verificador;
    }

    private boolean LlenarAtributosTelefono() {
        boolean verificador = false;
        proveedorTelefono = new ProveedorTelefono();
        int indiceCombox = this.jComboxTelefono.getSelectedIndex();

        if (this.ValidarCamposTelefono()) {
            System.out.println(this.txtNumero.getText());
            proveedorTelefono.setIdProveedor(idProveedorAux);// se inserta el idProveedor reuperado en el Telefono
            proveedorTelefono.setLada(this.txtLada.getText());
            proveedorTelefono.setNumero(this.txtNumero.getText());
            proveedorTelefono.setTipoTelefono(indiceCombox + 1);//aqui se le agrega el tipo de telefono sleccionado
            if (this.txtExtension.getText().isEmpty() == true) {
                proveedorTelefono.setExtension(0);
            } else {
                proveedorTelefono.setExtension(Integer.parseInt(this.txtExtension.getText()));
            }
            verificador = true;
        } else {
            JOptionPane.showMessageDialog(this, "Completar campos vacios");
            verificador = false;
        }
        return verificador;
    }

    private void registrar() throws Exception {
        bbl_ProveedorTelefono = new BLL_ProveedorTelefono();
        int verificador = 0;

        if (this.LlenarAtributos()) {

            idProveedorAux = u.ProveedorAdd(proveedor);//aqui recupero mi matricula del procedimiento
            System.out.println("id recuperado = " + this.idProveedorAux);
            if (this.LlenarAtributosTelefono()) {
                verificador = bbl_ProveedorTelefono.AddToDataBaseProveedorTelefono(dbCon, proveedorTelefono);
            }

            if (idProveedorAux != null && verificador != 0) {
                JOptionPane.showMessageDialog(this, "Datos registradados");
                // this.LimpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar");
            }
        }

    }

    private void registrarTelefono() throws Exception {
        int indiceCombox = this.jComboxTelefono.getSelectedIndex();
        int verificador = 0;
        if (indiceCombox + 1 == 1) {
            JOptionPane.showMessageDialog(this, "El telefono ya existe");
        } else {
            if (this.LlenarAtributosTelefono()) {
                verificador = bbl_ProveedorTelefono.AddToDataBaseProveedorTelefono(dbCon, proveedorTelefono);
                if (verificador != 0) {
                    JOptionPane.showMessageDialog(this, "Telefono registradado");
                    //this.LimpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el telefono");
                }
            }
        }
    }

    private void consultar() throws Exception {
        this.LimpiarCampos();
        proveedor = new Proveedor();
        testuniversity = new testUniversity();
        System.out.println(this.txtIdProveedor.getText());
        this.proveedor = testuniversity.ProveedorQry(this.txtIdProveedor.getText());
        this.txtNombre.setText(proveedor.getNombre());
        this.txtCalle.setText(proveedor.getCalle());
        this.txtColonia.setText(proveedor.getColonia());
        this.txtCiudad.setText(proveedor.getCiudad());
        this.txtCodigoPostal.setText(String.valueOf(proveedor.getCodigoPostal()));
        this.idProveedorAux = proveedor.getIdProveedor(); //obtiene el id del proveedor

        this.proveedorTelefono = new ProveedorTelefono();
        this.obtenerTodosLosTelefonosProveedor();

        if (this.listaTelefonoProveedor.size() > 0) {
            proveedorTelefono = (ProveedorTelefono) listaTelefonoProveedor.get(this.jComboxTelefono.getSelectedIndex());
            this.txtLada.setText(proveedorTelefono.getLada());
            if (proveedorTelefono.getExtension() == 0) {
                this.txtExtension.setText(" ");
            } else {
                this.txtExtension.setText(String.valueOf(proveedorTelefono.getExtension()));
            }
            this.txtNumero.setText(proveedorTelefono.getNumero());
        } else {
            JOptionPane.showMessageDialog(this, "No existen Telefonos");
        }
    }

    public void actalizarTelefono() throws Exception {
        int verificador = 0;
        int indiceCombox = this.jComboxTelefono.getSelectedIndex();

        bbl_ProveedorTelefono = new BLL_ProveedorTelefono();
        proveedorTelefono = new ProveedorTelefono();
        this.proveedorTelefono = (ProveedorTelefono) (this.listaTelefonoProveedor.get(indiceCombox));
        proveedorTelefono.setIdProveedor(proveedor.getIdProveedor());
        if (this.LlenarAtributosTelefono()) {
            verificador = bbl_ProveedorTelefono.updateProveedorTelefonoDatabase(dbCon, proveedorTelefono);
            System.out.println("verificador: " + verificador);
            if (verificador == 1) {
                JOptionPane.showMessageDialog(this, "Telefono Actualizado Exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Actualizacion Fallido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifica tus Datos");
        }
    }

    public void actualizar() throws Exception {
        int verificador = 0;
        bbl_Proveedor = new BLL_Proveedor();
        proveedor.setIdProveedor(this.idProveedorAux);

        if (this.LlenarAtributos()) {
            verificador = bbl_Proveedor.updateProveedorDataBase(dbCon, proveedor);

            System.out.println("probabdo = " + verificador);

            if (verificador == 1) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo Actualizar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifica tus datos");
        }
    }

    private void eliminar() throws Exception {
        bbl_Proveedor = new BLL_Proveedor();
        int verificadorProveedor, verificadorTelefono;
        // alumno.setMatricula(this.txtMatricula.getText());
        proveedor.setIdProveedor(idProveedorAux);
        verificadorTelefono = bbl_ProveedorTelefono.deleteProveedorTelefonoDatabase(dbCon, proveedor);
        verificadorProveedor = bbl_Proveedor.deleteProveedorDatabase(dbCon, proveedor);
        if (verificadorTelefono == 1 && verificadorProveedor == 1) {
            JOptionPane.showMessageDialog(this, "Proveedor Eliminado");
        } else {
            JOptionPane.showMessageDialog(this, "Eliminacion Fallida, Proveedor no Eliminado");
        }
    }

    private void obtenerTodosLosTelefonosProveedor() {
        try {
            BLL_ProveedorTelefono bbl_ProveedorTelefono = new BLL_ProveedorTelefono();
            this.listaTelefonoProveedor.addAll(u.ProveedorTelefonoQry(idProveedorAux));
        } catch (Exception e) {
            System.out.println("Problemas al obtener todosd los Telefonos proveedores ");
        }
    }

    private void eliminarTelefono() throws Exception {
        bbl_ProveedorTelefono = new BLL_ProveedorTelefono();
        proveedorTelefono = new ProveedorTelefono();
        int verificador = 0, indice = 0;

        String indiceCombox = this.jComboxTelefono.getSelectedItem().toString();
        for (int i = 0; i < this.listaTelefonoProveedor.size(); i++) {
            if (indiceCombox.equals("Personal")) {
                indice = this.obtenerIndiceAeliminar("Personal");
            } else if (indiceCombox.equals("Casa")) {
                indice = this.obtenerIndiceAeliminar("Casa");
            } else if (indiceCombox.equals("Oficina")) {
                indice = this.obtenerIndiceAeliminar("Oficina");
            }
        }

        proveedorTelefono = (ProveedorTelefono) this.listaTelefonoProveedor.get(indice);

        //    proveedorTelefono = (ProveedorTelefono) this.listaTelefonoProveedor.get(indiceCombox);
        verificador = bbl_ProveedorTelefono.deleteTelefonoDatabase(dbCon, proveedorTelefono);
        if (verificador != 0) {
            JOptionPane.showMessageDialog(this, "Telefono Eliminado Exitosamente");
            this.jComboxTelefono.removeItemAt(indice);
            this.listaTelefonoProveedor.remove(indice);
        } else {
            JOptionPane.showMessageDialog(this, "Eliminacion Fallida, Telefono No Eliminado");
        }

    }

    private int obtenerIndiceAeliminar(String telefono) {
        proveedorTelefono = new ProveedorTelefono();
        int indice = 0;
        for (int i = 0; i < this.listaTelefonoProveedor.size(); i++) {
            proveedorTelefono = (ProveedorTelefono) this.listaTelefonoProveedor.get(i);
            if (proveedorTelefono.getDescripcionTelefono().equals(telefono)) {
                indice = i;
            }
        }
        return indice;
    }

    private void crearComboBoxdProveedorTelefono() {
        proveedorTelefono = new ProveedorTelefono();
        int indiceCombox = this.jComboxTelefono.getSelectedIndex();
        for (int i = 0; i < this.listaTelefonoProveedor.size(); i++) {
            proveedorTelefono = (ProveedorTelefono) this.listaTelefonoProveedor.get(i);
            this.jComboxTelefono.addItem(proveedorTelefono.getDescripcionTelefono());
        }
    }
}
