/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unpa.winforms.ferreteria;

import java.sql.Connection;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import unpa.winforms.ferreteria.bll.BLL_Producto;
import unpa.winforms.ferreteria.el.Cliente;
import unpa.winforms.ferreteria.el.Producto;
import unpa.winforms.ferreteria.util.DbUtil;

/**
 *
 * @author chee <chee_unp@edu.mx>
 */
public class FrmVenta extends javax.swing.JFrame {

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtImporteTotal = new javax.swing.JTextField();
        txtFechaVenta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdDetalleVenta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxMano = new javax.swing.JCheckBox();
        jCheckBoxSujecion = new javax.swing.JCheckBox();
        jCheckBoxTuberiasDeSujecion = new javax.swing.JCheckBox();
        jCheckBoxElectricidad = new javax.swing.JCheckBox();
        jCheckBoxCimponentesDiversos = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta y Venta Detalle");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Cliente:"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 220, 30));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 30));

        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Direccion:"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Calle:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));
        jPanel5.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 240, 30));

        jLabel5.setText("Colonia:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel5.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 240, 30));

        jLabel6.setText("Ciudad:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel5.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 240, 30));

        jLabel7.setText("Codigo Postal:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel5.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 350, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 420));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Venta:"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Fecha Venta:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel10.setText("Importe Total:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel11.setText("Empleado:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setText("ID Venta:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel2.add(txtIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 230, 30));
        jPanel2.add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, 30));
        jPanel2.add(txtImporteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, 30));

        txtFechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVentaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 230, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 380, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Detalle De La Venta:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("ID Detalle Venta:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 20));

        txtIdDetalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDetalleVentaActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdDetalleVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 180, 30));

        jLabel12.setText("Producto:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel3.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, 30));

        jLabel14.setText("Precio:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, 30));

        jLabel15.setText("Cantidad:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 30));

        jLabel16.setText("SubTotal:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel3.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 30));

        jButton6.setText("Consultar Detalle venta");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, 30));

        jButton7.setText("Injsertar Detalle Venta");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 30));

        jButton8.setText("Actualizar Detalle Venta");
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 170, 30));

        jButton9.setText("Eliminar Detalle Venta");
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 160, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 300, 680));

        tablaProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Proveedor", "Existencia"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 830, 570));

        btnAceptar.setText("Mostrar Productos");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, 170, 60));

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 670, 160, 60));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Herramientas De:"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxMano.setText("Mano");
        jCheckBoxMano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxManoMouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBoxMano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jCheckBoxSujecion.setText("Sujecion");
        jPanel4.add(jCheckBoxSujecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jCheckBoxTuberiasDeSujecion.setText("Tuberias De Sujecion");
        jPanel4.add(jCheckBoxTuberiasDeSujecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jCheckBoxElectricidad.setText("Electricidad");
        jPanel4.add(jCheckBoxElectricidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jCheckBoxCimponentesDiversos.setText("ComponentesDiversos");
        jPanel4.add(jCheckBoxCimponentesDiversos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 820, 70));

        jButton1.setText("Insertar Venta");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, 150, 40));

        jButton3.setText("Consultar Venta");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 140, 40));

        jButton4.setText("Actualizar Venta");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 130, 40));

        jButton5.setText("Eliminar Venta");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxManoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxManoMouseClicked
        
    }//GEN-LAST:event_jCheckBoxManoMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        try {
            this.obtenerListaProductos();
        } catch (Exception ex) {
            Logger.getLogger(FrmVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtFechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVentaActionPerformed

    private void txtIdDetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDetalleVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDetalleVentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBoxCimponentesDiversos;
    private javax.swing.JCheckBox jCheckBoxElectricidad;
    private javax.swing.JCheckBox jCheckBoxMano;
    private javax.swing.JCheckBox jCheckBoxSujecion;
    private javax.swing.JCheckBox jCheckBoxTuberiasDeSujecion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtFechaVenta;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdDetalleVenta;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtImporteTotal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables
    private Connection dbCon;
    private Cliente  cliente;
    BLL_Producto bll_producto=null;
     Calendar fecha = new GregorianCalendar();
     int ano = fecha.get(Calendar.YEAR);
     int mes = Calendar.DAY_OF_WEEK;
     int dia = fecha.get(Calendar.DAY_OF_MONTH);
     private  String fechaActual=String.valueOf(dia)+String.valueOf(mes)+String.valueOf(ano);
     
     /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
        this.Init();
        
    }
    
      public void Init() {
        try {
            producto = new Producto();
            cliente = new Cliente();
            dbCon = DbUtil.getInstance().getConnection();
            
        } catch (Exception e) {
            System.out.println("eroor en el metodo Init");
        }
    }
    
    
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    LinkedList <Producto> listaProductos=new LinkedList <Producto>();
    Producto producto =null;
    
    
    
    
    
    

    private void obtenerListaProductos() throws Exception{
        bll_producto =new BLL_Producto();
        if(this.jCheckBoxMano.isSelected()){
            this.listaProductos=this.bll_producto.QueryAllProductoDataBase(dbCon, 1);
            
        }
        else if(this.jCheckBoxSujecion.isSelected()){
           this.listaProductos=this.bll_producto.QueryAllProductoDataBase(dbCon, 2);
        }
        else if(this.jCheckBoxTuberiasDeSujecion.isSelected()){
            this.listaProductos=this.bll_producto.QueryAllProductoDataBase(dbCon, 3);
        }    
        else if(this.jCheckBoxElectricidad.isSelected()){
            this.listaProductos=this.bll_producto.QueryAllProductoDataBase(dbCon, 4);
        }
        else if(this.jCheckBoxCimponentesDiversos.isSelected()){
            this.listaProductos=this.bll_producto.QueryAllProductoDataBase(dbCon, 5);
        }
        
       
       this.consultarTesis();
       
       System.out.println(this.tablaProductos.getValueAt(0,1));
    }

     private void consultarTesis(){
       DefaultTableModel modelo=new DefaultTableModel();
        Object [] object= new Object[10];
        this.tablaProductos.setModel(modelo);
        modelo.addColumn("producto");
        modelo.addColumn("Precio");
       modelo.addColumn("Proveedor");
       modelo.addColumn("Existencia");
       
        for(int x=0;x<listaProductos.size();x++){
            object[0]=listaProductos.get(x).getNombre();
            object[1]=listaProductos.get(x).getPrecio();
            object[2]=listaProductos.get(x).getMarca();
            object[3]=listaProductos.get(x).getExistencia();
        
//            if(listaProductos.get(x).isBeca()){
//                object[3]="Si";
//            }else{
//                object[3]="No";
//            }
//            if(listaProductos.get(x).isDisponible()){
//                object[4]="Si";
//            }else{
//                object[4]="No";
//            }
        
            modelo.addRow(object); 
        }  
    }


}
